air3d_app/main/routes.py
from flask import (
    request,
    redirect,
    render_template,
    url_for,
    Blueprint,
    session,
    flash,
    jsonify
)
from werkzeug.utils import secure_filename
from flask_uploads import UploadSet, IMAGES, configure_uploads
from bson.objectid import ObjectId
import requests
import os
from dotenv import load_dotenv
from air3d_app import app, db, socketio
from flask_login import login_user, logout_user, login_required, current_user
from datetime import date, datetime
from air3d_app.models import User, Profile, Requests, Design
from air3d_app.main.forms import ProfileForm, RequestForm, DesignForm
from air3d_app import bcrypt
import stripe

main = Blueprint('main', __name__)


# Create Upload sets for offers and design requests
offers = UploadSet("offers", IMAGES)
design_requests = UploadSet("requests", IMAGES)
configure_uploads(app, (offers, design_requests))

# Set Stripe Variables
load_dotenv()

stripe_keys = {
    "secret_key": os.getenv("STRIPE_SECRET_KEY"),
    "publishable_key": os.getenv("STRIPE_PUBLISHABLE_KEY"),
    # "endpoint_secret": os.environ["STRIPE_ENDPOINT_SECRET"],
}

stripe.api_key = stripe_keys["secret_key"]


# Homepage
@main.route('/')
def home():
    '''Display homepage'''
    return render_template('home.html')


# Product Offers
@main.route('/product-offers')
def product_offers():
    '''Display product offers'''
    return render_template('product-offers.html')


@main.route('/order-form', methods=['GET', 'POST'])
def create_request():
    """Create a request for a product."""
    form = RequestForm()
    if form.validate_on_submit():
        new_request = Requests(
            username=form.username.data,
            email=form.email.data,
            description=form.description.data
        )
        db.session.add(new_request)
        db.session.commit()

        flash('New request submitted successfully.')
        return redirect(url_for('main.home'))

    # if form was not valid, or was not submitted yet
    return render_template('order-form.html', form=form)


@main.route('/product-requests')
@login_required
def product_requests():
    """View list of all submitted product requests."""
    all_requests = Requests.query.all()
    return render_template('product-requests.html',
                           all_requests=all_requests)


@main.route('/create_profile', methods=['GET', 'POST'])
@login_required
def create_profile():
    """Create a public profile."""
    form = ProfileForm()
    # if form was submitted and contained no errors
    if form.validate_on_submit():
        new_profile = Profile(
            username=form.username.data
        )
        db.session.add(new_profile)
        db.session.commit()

        flash('New profile was created successfully.')
        return redirect(url_for('main.home'))

    # if form was not valid, or was not submitted yet
    return render_template('create_profile.html', form=form)


# Check to make sure the upload type is allowed
def allowed_file(filename):
    return '.' in filename and \
           filename.rsplit('.', 1)[1].lower() in {'png', 'jpg', 'jpeg', 'gif'}


# Order Form
@main.route('/order-form', methods=['GET', 'POST'])
def order_form():
    '''Display order form'''
    # Handle file upload
    if request.method == 'POST' and 'request' in request.files:
        design_requests.save(request.files['request'])
        flash("Request submitted")
        return render_template('order-form.html')
    return render_template('order-form.html')


@main.route('/profile/<full_name>')
def profile(full_name):
    """View public profile of a user."""
    # user = User.query.filter_by(username=username).one()
    profile = Profile.query.filter_by(username=current_user.username).first()
    return render_template('profile.html', profile=profile)


# Product Offers Upload Form
@main.route('/design-upload-form')
def design_upload_form():
    '''Display design upload form'''
    # Handle file upload
    if request.method == 'POST' and 'offer' in request.files:
        offers.save(request.files['offer'])
        flash("Offer submitted")
        return render_template('design-upload-form.html')
    return render_template('design-upload-form.html')


# Chat Page
@main.route('/chat', methods=['GET', 'POST'])
@login_required
def chat():
    return render_template('chat.html')


def receive_message(methods=['GET', 'POST']):
    print("New Message")


@socketio.on('message')
def message(json):
    print(str(json))
    socketio.emit('response', json, callback=receive_message)



# Stripe routes

# Homepage
@main.route('/purchase')
def purchase():
    '''Display purchase page'''
    return render_template('stripe.html')

@main.route("/config")
def get_publishable_key():
    stripe_config = {"publicKey": stripe_keys["publishable_key"]}
    return jsonify(stripe_config)

@main.route("/create-checkout-session")
def create_checkout_session():
    domain_url = "https://air3d.herokuapp.com/"
    stripe.api_key = stripe_keys["secret_key"]

    try:
        # Create new Checkout Session for the order
        # Other optional params include:
        # [billing_address_collection] - to display billing address details on the page
        # [customer] - if you have an existing Stripe Customer ID
        # [payment_intent_data] - capture the payment later
        # [customer_email] - prefill the email input in the form
        # For full details see https://stripe.com/docs/api/checkout/sessions/create

        # ?session_id={CHECKOUT_SESSION_ID} means the redirect will have the session ID set as a query param
        checkout_session = stripe.checkout.Session.create(
            success_url=domain_url + "success?session_id={CHECKOUT_SESSION_ID}",
            # success_url=domain_url + "success?session_id=price_1KHG2eJSgrm4MfoGb7iF4qFA",
            cancel_url=domain_url + "cancelled",
            payment_method_types=["card"],
            mode="payment",
            line_items=[
                {
                    "name": "3D Print Service",
                    "quantity": 1,
                    "currency": "usd",
                    "amount": "2000",
                }
            ]
        )
        return jsonify({"sessionId": checkout_session["id"]})
    except Exception as e:
        return jsonify(error=str(e)), 403


@main.route("/success")
def success():
    return render_template("success.html")


@main.route("/cancelled")
def cancelled():
    return render_template("cancelled.html")


@main.route("/webhook", methods=["POST"])
def stripe_webhook():
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get("Stripe-Signature")

    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, stripe_keys["endpoint_secret"]
        )

    except ValueError as e:
        # Invalid payload
        return "Invalid payload", 400
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return "Invalid signature", 400

    # Handle the checkout.session.completed event
    if event["type"] == "checkout.session.completed":
        print("Payment was successful.")
        # TODO: run some custom code here

    return "Success", 200

air3d_app/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>Air3D</title>
        <!-- Link Bootstrap 4 to this HTML file -->
        <link
            rel="stylesheet"
            href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        />
        <!-- Bootstrap Theme -->
        <link rel="stylesheet" href="../static/bootstrap.min.css" />
        <!-- Custom styles -->
        <link rel="stylesheet" href="../static/style.css" />
    </head>
    <body>
        <!-- NAVBAR -->
        <!-- previously with bg-dark -->
        <nav class="navbar navbar-expand-lg navbar-dark">
            <a class="navbar-brand" href="{{ url_for('main.home') }}">Air3D</a>
            <div class="navbar-nav">
                <a
                    class="nav-item nav-link active"
                    href="{{ url_for('main.home') }}"
                    >Home <span class="sr-only">(current)</span></a
                >
                <a
                    class="nav-item nav-link"
                    href="{{ url_for('main.product_offers') }}"
                    >Product Offers</a
                >
                <a
                    class="nav-item nav-link"
                    href="{{ url_for('main.product_requests') }}"
                    >Product Requests</a
                >
                <a
                    class="nav-item nav-link"
                    href="{{ url_for('main.create_request') }}"
                    >Order Form</a
                >

                {% if current_user.is_authenticated %}
                <div class="navbar-nav">
                    <a
                        class="nav-item nav-link"
                        href="{{ url_for('main.design_upload_form') }}"
                        >Design Upload Form</a
                    >
                    <a
                        class="nav-item nav-link"
                        href="{{ url_for('main.chat') }}"
                        >Chat</a
                    >
                    <a class="nav-item nav-link" href="/logout">Log Out</a>
                </div>

                {% else %}
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="btn btn-secondary" href="/login">Sign in</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn btn-primary" href="/signup">Sign up</a>
                    </li>
                </ul>
                {% endif %}
            </div>
        </nav>

        {% if current_user.is_authenticated %}
        <p>You are logged in as {{ current_user.username }}</p>
        {% endif %} {% for message in get_flashed_messages() %}
        <p>{{ message }}</p>
        {% endfor %} {% block content %}{% endblock %}

        <!-- FOOTER -->
        <!-- previously with bg-secondary -->
        <footer class="p-2 text-white">&copy; 2022 Air3D, Inc.</footer>

        <!-- JS Scripts -->
        <script
            src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"
        ></script>
        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
            crossorigin="anonymous"
        ></script>
        {% block scripts %} {% endblock scripts %}
    </body>
</html>

air3d_app/templates/cancelled.html
{% extends "base.html" %}

{% block content %}
  <section class="section">
    <div class="container">
      <p>Your payment was cancelled.</p>
    </div>
  </section>
{% endblock %}

air3d_app/templates/chat.html
{% extends 'base.html' %} {% block content %}

<h3 style="color: #ccc; font-size: 30px">No message yet..</h3>
<div class="message_holder"></div>

<form id="message_box" method="POST">
    <input type="text" class="message" placeholder="Type message here" />
    <input type="submit" />
</form>

{% endblock %} {% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.4.1/socket.io.min.js"></script>
<script type="text/javascript">
    var current_user = "{{ current_user.username }}";
</script>
<script src="../static/index.js"></script>
{% endblock scripts %}

air3d_app/templates/design-upload-form.html
{% extends 'base.html' %} {% block content %}

<!-- DESIGN UPLOAD FORM -->
<h2 class="bg-light text-center pt-3 pb-5 mb-0">
    Upload your product design here.
</h2>
<form
    method="POST"
    enctype="multipart/form-data"
    action="{{ url_for('main.design_upload_form')
}}"
    class="bg-light mb-0"
>
    <div class="form-group row">
        <label for="inputEmail" class="col-sm-2 offset-sm-1 col-form-label mt-5"
            >Email</label
        >
        <div class="col-sm-6">
            <input
                type="email"
                class="form-control mt-5 mb-5"
                id="inputEmail"
            />
        </div>
    </div>
    <div class="form-group">
        <label for="description" class="offset-sm-1">Description</label>
        <textarea
            class="form-control col-sm-10 offset-sm-1 mb-5"
            id="description"
            rows="3"
        ></textarea>
    </div>
    <div class="form-group">
        <label class="offset-sm-1" for="imageFiles"
            >Choose an image for your product:</label
        >
        <input
            type="file"
            class="form-control-file offset-sm-1 mb-5"
            id="imageFiles"
            name="offer"
        />
    </div>
    <div class="form-group row">
        <label for="priceOffer" class="col-sm-2 col-form-label offset-sm-1"
            >Price Offer ($0 to $100)</label
        >
        <div class="col-sm-10">
            <input
                type="number"
                class="form-control offset-sm-1 mb-5"
                id="priceOffer"
            />
        </div>
    </div>
    <div class="form-group row mb-0">
        <div class="col-sm-2 offset-sm-4">
            <button type="reset" class="btn btn-secondary mb-3">Reset</button>
        </div>
        <!-- <div class="col-sm-2">
            <button
                type="button"
                class="btn btn-primary mb-3"
                data-toggle="modal"
                data-target="#submitModal"
            >
                Submit Order
            </button>  
        </div> -->
        <div class="col-sm-2 offset-sm-4">
            <input type="submit" class="btn btn-secondary mb-3" value="Submit">
        </div>
    </div>
</form>

<!-- Modal -->
<div
    class="modal fade"
    id="submitModal"
    tabindex="-1"
    aria-labelledby="submitModalLabel"
    aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="submitModalLabel">
                    Confirm Submission
                </h5>
                <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                >
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you ready to upload this design form?</p>
            </div>
            <div class="modal-footer">
                <button
                    type="button"
                    class="btn btn-secondary"
                    data-dismiss="modal"
                >
                    Cancel
                </button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

air3d_app/templates/home.html
{% extends 'base.html' %} {% block content %}

<!-- HERO -->
<div class="jumbotron text-center hero-background-img">
    <h1>Air3D</h1>
    <p class="lead">The next stage of the consumer 3D printing revolution</p>
    <a href="#learn-more" class="btn btn-primary">Learn More</a>
</div>

<!-- BENEFITS -->
<section id="learn-more">
    <div class="container pb-5 pt-5">
        <div class="row">
            <div class="col-lg-4">
                <h3>Simple</h3>
                <p class="lead">
                    No need to create the CAD file! Just send a description of
                    your desired project to the 3D printer owner you connect
                    with.
                </p>
            </div>
            <div class="col-lg-4">
                <h3>Convenient</h3>
                <p class="lead">
                    Using 3D printers is very complicated and requires lots of
                    time and hard work to master. You can avoid this by
                    leveraging the expertise of existing 3D printer owners.
                </p>
            </div>
            <div class="col-lg-4">
                <h3>Affordable</h3>
                <p class="lead">
                    Pay for each project instead of spending up to thousands of
                    dollars on installing and maintaining a desktop 3D printer.
                </p>
            </div>

            <!-- Image of a 3D printer -->
            <div class="row m-5">
                <div class="col-lg-6">
                    <img
                        src="../static/assets/benefits-img.jpg"
                        class="img-fluid rounded"
                    />
                </div>
                <div class="col-lg-6">
                    <h3>Benefits to Owners</h3>
                    <p>
                        Owners of 3D printers can earn side income by fulfilling
                        order requests. More experienced owners can charge
                        higher fees for orders that require greater skill or
                        more material to build. Of course, less experienced
                        owners of 3D printers can still earn money by taking on
                        simpler projects, which can help with developing 3D
                        printing expertise.
                    </p>
                    <p>
                        To get started, either peruse pending requests
                        <a
                            href="./product-requests.html"
                            data-toggle="tooltip"
                            title="Product Request Form"
                            >here</a
                        >
                        or submit your own CAD design file and specs to
                        potential clients
                        <a
                            href="./design-upload-form.html"
                            data-toggle="tooltip"
                            title="Design Upload Form"
                        >
                            here</a
                        >.
                    </p>
                </div>
            </div>

            <!-- Video embed -->
            <!-- <div class="embed-responsive embed-responsive-16by9 m-5">
                <iframe
                    class="embed-responsive-item"
                    src="https://www.youtube.com/embed/3LBTkLsjHGQ"
                    allowfullscreen
                ></iframe>
            </div> -->
        </div>
    </div>
</section>

<!-- CALL TO ACTION -->
<div class="jumbotron text-center mb-0">
    <p class="lead mb-4">Sign Up for More Infomation</p>
    <div class="d-flex justify-content-center">
        <form action="#" class="form-inline">
            <input
                type="text"
                class="form-control mb-2 mr-sm-2"
                placeholder="Email"
            />
            <button type="submit" class="btn btn-primary mb-2">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

air3d_app/templates/login.html
{% extends 'base.html' %} {% block content %}

<h1>Log In</h1>

<form action="/login" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }} {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }} {{ form.password }}
        <ul>
            {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        <a href="#" style="margin-bottom: 5%">Forgot Password?</a>

        <a href="./signup.html" style="margin-bottom: 5%"
            >Don't have an account? Create one here</a
        >

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

air3d_app/templates/order-form.html
{% extends 'base.html' %} {% block content %}

<!-- ORDER FORM -->
<h2 class="bg-light text-center pt-3 pb-5 mb-0">
    Place an order here for your desired product.
</h2>
<form
    method="POST"
    enctype="multipart/form-data"
    action="{{ url_for('main.order_form')
}}"
    class="bg-light mb-0"
>
    <div class="form-group row">
        <label for="inputEmail" class="col-sm-2 offset-sm-1 col-form-label mt-5"
            >Email</label
        >
        <div class="col-sm-6">
            <input
                type="email"
                class="form-control mt-5 mb-5"
                id="inputEmail"
            />
        </div>
    </div>
    <div class="form-group">
        <label for="description" class="offset-sm-1">Description</label>
        <textarea
            class="form-control col-sm-10 offset-sm-1 mb-5"
            id="description"
            rows="3"
        ></textarea>
    </div>
    <div class="form-group">
        <label for="cadFile" class="offset-sm-1"
            >Upload CAD file (optional):</label
        >
        <input
            type="file"
            class="form-control-file offset-sm-1 mb-5"
            id="cadFile"
            name="request"
        />
    </div>
    <div class="form-group row">
        <label for="priceOffer" class="col-sm-2 col-form-label offset-sm-1"
            >Expected Price ($0 to $100)</label
        >
        <div class="col-sm-10">
            <input
                type="number"
                class="form-control offset-sm-1 mb-5"
                id="priceOffer"
            />
        </div>
    </div>
    <div class="form-group row mb-0">
        <div class="col-sm-2 offset-sm-4">
            <button type="reset" class="btn btn-secondary mb-3">Reset</button>
        </div>
        <div class="col-sm-2">
            <button
                type="submit"
                class="btn btn-primary mb-3"
            >
                Submit Order
            </button>
        </div>
    </div>
</form>

<!-- Modal -->
<div
    class="modal fade"
    id="submitModal"
    tabindex="-1"
    aria-labelledby="submitModalLabel"
    aria-hidden="true"
>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="submitModalLabel">
                    Confirm Submission
                </h5>
                <button
                    type="button"
                    class="close"
                    data-dismiss="modal"
                    aria-label="Close"
                >
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you ready to submit this order form?</p>
            </div>
            <div class="modal-footer">
                <button
                    type="button"
                    class="btn btn-secondary"
                    data-dismiss="modal"
                >
                    Cancel
                </button>
                <button type="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
    </div>
</div>

{% endblock %}

air3d_app/templates/product-offers.html
{% extends 'base.html' %} {% block content %}

<!-- List -->
<div class="list-group" style="height: 100vh">
    <a
        href="{{ url_for('main.purchase') }}"
        class="list-group-item list-group-item-action"
    >
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1" style="color: azure">iPhone 12 Case</h5>
            <small>1 day ago</small>
        </div>
        <p class="mb-1">
            A sturdy case designed with precision to prefectly fit the iPhone
            12.
        </p>
        <small>Price Offer: $21</small>
    </a>
    <a
        href="{{ url_for('main.purchase') }}"
        class="list-group-item list-group-item-action"
    >
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1" style="color: azure">Water Bottle</h5>
            <small>3 days ago</small>
        </div>
        <p class="mb-1">A reusable water bottle with a capacity of 18oz.</p>
        <small>Price Offer: $16</small>
    </a>
    <a
        href="{{ url_for('main.purchase') }}"
        class="list-group-item list-group-item-action"
    >
        <div class="d-flex w-100 justify-content-between">
            <h5 class="mb-1" style="color: azure">Raspberry Pi Case</h5>
            <small>6 days ago</small>
        </div>
        <p class="mb-1">
            A semi-transparent case that fits firmly and snugly around the
            unique contours of the Raspberry Pi.
        </p>
        <small>Price Offer: $9</small>
    </a>
</div>

{% endblock %}

air3d_app/templates/product-requests.html
{% extends 'base.html' %} {% block content %}

<!-- Filler -->
<h5 style="height: 100vh; padding-top: 6em; text-align: center">
    There are currently no product requests. Please try checking back later.
</h5>

{% endblock %}

air3d_app/templates/signup.html
{% extends 'base.html' %} {% block content %}

<h1>Sign Up</h1>

<form action="/signup" method="POST">
    {{ form.csrf_token }}
    <fieldset>
        <legend>Enter your credentials</legend>

        {{ form.username.label }} {{ form.username }}
        <ul>
            {% for error in form.username.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.password.label }} {{ form.password }}
        <ul>
            {% for error in form.password.errors %}
            <li class="error">{{ error }}</li>
            {% endfor %}
        </ul>

        {{ form.submit }}
    </fieldset>
</form>

{% endblock %}

air3d_app/templates/stripe.html
{% extends "base.html" %} {% block content %}
<section class="section">
    <div class="container">
        <button class="button is-primary" id="submitBtn">Purchase!</button>
    </div>
</section>
{% endblock %} {% block scripts %}
<!-- Stripe JS -->
<script src="https://js.stripe.com/v3/"></script>
<script src="{{ url_for('static', filename='main.js') }}"></script>
<script
    defer
    src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"
></script>
{% endblock scripts %}

air3d_app/templates/success.html
{% extends "base.html" %} {% block content %}
<section class="section">
    <div class="container">
        <p>Great success! Your payment went through.</p>
    </div>
</section>
{% endblock %}